"""Canonical, tamper-evident evidence records."""

from evidence.chain import (
    GENESIS_HASH,
    HASH_ALGORITHM,
    SERIALIZATION,
    TRUSTED_EVIDENCE_SOURCES,
    EvidenceIntegrityError,
    EvidenceRecord,
    ProtectedHead,
    TrustedEvidenceSource,
    append,
    canonical_json_bytes,
    chain_id_for,
    freeze_json,
    require_append_only_prefix,
    thaw_json,
    verify,
    verify_prefix,
    verify_transition,
)

__all__ = [
    "GENESIS_HASH",
    "HASH_ALGORITHM",
    "SERIALIZATION",
    "TRUSTED_EVIDENCE_SOURCES",
    "EvidenceIntegrityError",
    "EvidenceRecord",
    "ProtectedHead",
    "TrustedEvidenceSource",
    "append",
    "canonical_json_bytes",
    "chain_id_for",
    "freeze_json",
    "require_append_only_prefix",
    "thaw_json",
    "verify",
    "verify_prefix",
    "verify_transition",
]
